# Generated by Django 4.2.7 on 2024-02-09 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buu",
            name="sendTo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buus_received",
                to="user.user",
            ),
        ),
    ]
