# Generated by Django 4.2.7 on 2024-02-09 21:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_buu_sendto"),
    ]

    operations = [
        migrations.RenameField(
            model_name="buu",
            old_name="sendTo",
            new_name="receiver",
        ),
        migrations.RenameField(
            model_name="buu",
            old_name="user",
            new_name="sender",
        ),
    ]
