# Generated by Django 4.2.7 on 2024-02-15 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("buser", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buser",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=20, unique=True)),
                ("email", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=20)),
                ("description", models.TextField(max_length=100)),
                (
                    "background",
                    models.ImageField(
                        blank=True, null=True, upload_to="busers_backgrounds"
                    ),
                ),
                (
                    "profile",
                    models.ImageField(
                        blank=True, null=True, upload_to="busers_profiles"
                    ),
                ),
                (
                    "followers",
                    models.ManyToManyField(
                        related_name="followers_set", to="buser.buser"
                    ),
                ),
                (
                    "following",
                    models.ManyToManyField(
                        related_name="following_set", to="buser.buser"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Buu",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField(max_length=100)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buus_received",
                        to="buser.buser",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="buser.buser"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ret",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField(max_length=300)),
                (
                    "media",
                    models.ImageField(blank=True, null=True, upload_to="ret_media"),
                ),
                ("comret", models.BooleanField(default=False)),
                ("isreret", models.BooleanField(default=False)),
                (
                    "likes",
                    models.ManyToManyField(related_name="liked", to="buser.buser"),
                ),
                (
                    "refbuu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ret_responses",
                        to="buser.buu",
                    ),
                ),
                (
                    "replies",
                    models.ManyToManyField(
                        blank=True, related_name="replyto", to="buser.ret"
                    ),
                ),
                (
                    "rerets",
                    models.ManyToManyField(
                        blank=True, related_name="rerets", to="buser.buser"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rets",
                        to="buser.buser",
                    ),
                ),
            ],
        ),
    ]
