# Generated by Django 4.2.7 on 2024-03-23 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("buser", "0002_alter_ret_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ret",
            name="replies",
        ),
        migrations.AddField(
            model_name="ret",
            name="replyto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="buser.ret",
            ),
        ),
    ]
