# Generated by Django 4.2.7 on 2024-02-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buser", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buser",
            name="followers",
            field=models.ManyToManyField(
                blank=True, default=[], related_name="followers_set", to="buser.buser"
            ),
        ),
        migrations.AlterField(
            model_name="buser",
            name="following",
            field=models.ManyToManyField(
                blank=True, default=[], related_name="following_set", to="buser.buser"
            ),
        ),
    ]
