# Generated by Django 4.2.7 on 2024-03-14 00:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("buser", "0002_alter_buser_description"),
        ("buser", "0002_alter_buser_options_alter_buser_managers_and_more"),
    ]

    operations = []
