# Generated by Django 4.2.7 on 2024-03-30 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buser", "0003_remove_ret_replies_ret_replyto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ret",
            name="isreret",
        ),
        migrations.AlterField(
            model_name="ret",
            name="rerets",
            field=models.ManyToManyField(
                blank=True, related_name="rereteds", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
