# Generated by Django 4.2.7 on 2024-03-14 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buser", "0004_remove_buser_followers_remove_buser_following_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buser",
            name="followers",
            field=models.ManyToManyField(
                blank=True,
                default=[],
                related_name="followers_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="buser",
            name="following",
            field=models.ManyToManyField(
                blank=True,
                default=[],
                related_name="following_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
