# Generated by Django 4.2.7 on 2024-03-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buser", "0004_alter_buser_description_alter_buser_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buser",
            name="description",
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
