# Generated by Django 4.2.7 on 2024-03-30 17:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buser", "0004_remove_ret_isreret_alter_ret_rerets"),
    ]

    operations = [
        migrations.AddField(
            model_name="buser",
            name="rereteds",
            field=models.ManyToManyField(
                blank=True, related_name="rereteds_users", to="buser.ret"
            ),
        ),
        migrations.AlterField(
            model_name="ret",
            name="rerets",
            field=models.ManyToManyField(
                blank=True, related_name="rereteds_rets", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
