# Generated by Django 4.2.7 on 2024-03-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buser", "0005_alter_buser_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
