# Generated by Django 4.2.7 on 2024-03-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buser", "0005_buser_followers_buser_following"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buser",
            name="description",
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
