# Generated by Django 4.2.7 on 2024-03-15 19:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("buser", "0006_alter_buser_is_active"),
        ("buser", "0007_alter_buser_is_active"),
    ]

    operations = []
